### ISSUE TITLE
train_res_unet.py

### ISSUE THREAD

**Issue by lxg15066629402** [nitsaick/kits19-challenge#1]
KeyError: 'dc_per_case_2'

**Comment by lxg15066629402** [comment]
thank you




------------------ 原始邮件 ------------------
发件人: "Nick Tsai"<notifications@github.com>; 
发送时间: 2019年9月11日(星期三) 中午12:11
收件人: "nitsaick/kits19-challenge"<kits19-challenge@noreply.github.com>; 
抄送: "Jone"<it_lxg@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [nitsaick/kits19-challenge] train_res_unet.py (#1)




Closed #1 via 101315b.

**Comment by lxg15066629402** [comment]
cc3d is Module？？ 




------------------ 原始邮件 ------------------
发件人: "Nick Tsai"<notifications@github.com>; 
发送时间: 2019年9月11日(星期三) 中午12:11
收件人: "nitsaick/kits19-challenge"<kits19-challenge@noreply.github.com>; 
抄送: "Jone"<it_lxg@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [nitsaick/kits19-challenge] train_res_unet.py (#1)




Closed #1 via 101315b.

**Comment by nitsaick** [comment]
cc3d is a 3rd party package [connected-components-3d](https://github.com/seung-lab/connected-components-3d/)
