### ISSUE TITLE
The dimensions of the data and data labels do not match 

### ISSUE THREAD

**Issue by lxg15066629402** [nitsaick/kits19-challenge#3]
I found that the dimension of the data is 4 dimensions, but the dimension of the data is 3 dimensions, so there is a problem in calculating the loss.

**Comment by nitsaick** [comment]
Can you tell me where is the actually wrong code?
Because I can get the normal loss value when running the code on my server.
And in loss/generalized_dice_loss.py, forward() will check the data dimension, if data is 3 dimension then you will get error.
