### ISSUE TITLE
cc3d module

### ISSUE THREAD

**Issue by lidashuai123** [nitsaick/kits19-challenge#5]
Sorry, I cannot find the cc3d module. Did you create this module yourself? Thanks

**Comment by nitsaick** [comment]
No, cc3d is a 3rd party package [connected-components-3d](https://github.com/seung-lab/connected-components-3d/).

Use this command to install cc3d:
```bash
pip install connected_components_3d
```

**Comment by lidashuai123** [comment]
I really appreciate it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nick Tsai"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月13日(星期五) 下午3:19
收件人:&nbsp;"nitsaick/kits19-challenge"<kits19-challenge@noreply.github.com&gt;;
抄送:&nbsp;"大葱"<2714241070@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nitsaick/kits19-challenge] cc3d module (#5)




No, cc3d is a 3rd party package connected-components-3d.
 
Use this command to install cc3d:
 pip install connected_components_3d
