### ISSUE TITLE
Data_Aug

### ISSUE THREAD

**Issue by JiangYuhan1996** [nitsaick/kits19-challenge#6]
Hi,
I have a question that after I used the MedicalTransform model to augment the image, I printed the effect image and found that the label of the image has not changed: the first line is the image and label when the image is not augmented, and the second line is the augmented image And labels.Is it right?
![image](https://user-images.githubusercontent.com/56461519/70858207-83516280-1f38-11ea-81f3-1c0d3058e33c.png)
Best,
Jiang

**Comment by nitsaick** [comment]
Is that mean you use MedicalTransform to your own code?
My code does not rotate the image 90 degrees to the left.
I need full code when printing these 4 images.

**Comment by JiangYuhan1996** [comment]
Thanks for your reply, and this is the code I Used to print:
img_size = (512, 512)
transform = None
dataset = KiTS19(data_path, stack_num=3, spec_classes=[0, 1, 2], img_size=img_size,
                 use_roi=None, roi_file='roi.json',
                 train_transform=transform, valid_transform=transform)
img = dataset[288]['image']
img = img.numpy()
img = img.transpose(2, 1, 0)
transform2 = MedicalTransform(output_size=img_size, roi_error_range=15, use_roi=True)
dataset2 = KiTS19(data_path, stack_num=3, spec_classes=[0, 1, 2], img_size=img_size,
                 use_roi=True, roi_file='roi.json',
                 train_transform=transform2, valid_transform=transform2)
img2 = dataset2[388]['image']
img2 = img2.numpy()
img2 = img2.transpose(2, 1, 0)
plt.subplot(221)
plt.imshow(img)
plt.subplot(222)
plt.imshow(label)
plt.subplot(223)
plt.imshow(img2)
plt.subplot(224)
plt.imshow(label2)
plt.show()

**Comment by nitsaick** [comment]
I don't see where "label" and "label2" you get in your code.

But I write a similar code and can get the correct augmented image and label.

```python
from dataset import KiTS19
from dataset.transform import MedicalTransform
import matplotlib.pyplot as plt

data_path = 'data'
img_size = (512, 512)
transform = None
dataset = KiTS19(data_path, stack_num=3, spec_classes=[0, 1, 2], img_size=img_size,
use_roi=True, roi_file='roi.json',
train_transform=transform, valid_transform=transform)

data = dataset[388]
img = data['image']
img = img.numpy()
img = img[1]
label = data['label']
label = label.numpy()

transform2 = MedicalTransform(output_size=img_size, roi_error_range=15, use_roi=True)
dataset2 = KiTS19(data_path, stack_num=3, spec_classes=[0, 1, 2], img_size=img_size,
use_roi=True, roi_file='roi.json',
train_transform=transform2, valid_transform=transform2)

data2 = dataset2[388]
img2 = data2['image']
img2 = img2.numpy()
img2 = img2[1]
label2 = data2['label']
label2 = label2.numpy()

plt.subplot(221)
plt.imshow(img)
plt.subplot(222)
plt.imshow(label)
plt.subplot(223)
plt.imshow(img2)
plt.subplot(224)
plt.imshow(label2)
plt.show()
```

![image](https://user-images.githubusercontent.com/5717426/70894643-609e7700-2028-11ea-988f-591147859085.png)

**Comment by JiangYuhan1996** [comment]
wow! I know where I was wrong!!!!!! Thanks very much for your contribution and your patience.
